default: &default
  adapter: postgresql
  host: <%= ENV.fetch("POSTGRES_HOST", "postgres") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: my_rails_app_dev

test:
  <<: *default
  database: my_rails_app_test

production:
  <<: *default
  database: my_rails_app
